[[main]]
    name = 'Accueil'
    pageRef = '/'
    weight = 10
[[main]]
    name = 'Articles'
    pageRef = '/posts/'
    weight = 20
[[main]]
    name = 'Notes'
    pageRef = '/notes/'
    weight = 30
[[main]]
    name = 'À propos'
    pageRef = '/about'
    weight = 50