[build] 
  publish = "public"
  
[context.production]
  command = "hugo --gc"
  
[context.production.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
    
[context.deploy-preview.environment]
  HUGO_VERSION = "0.119.0"
  HUGO_ENV = "preview"
